logging:
  level:
    org:
      springframework: OFF
    maersk:
      com: INFO
spring:
  main:
    banner-mode: CONSOLE
  banner:
    location: banner.txt            
  security:
     enabled: disabled
     user:
       name: monitor
       password: monitor123            
ibm:
  mq:
    multiInstance: false
    queueManager: QMAP01
    channel: MQ.MONITOR.SVRCONN
    connName: localhost(1501), localhost(1442)
    sslCipherSpec2:
    sslCipherSpec: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    sslCipherSpec1: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    ibmCipherMapping: false
    useSSL: true
    user: MQmon01
    password: Passw0rd
    authenricateUsingCSP: true
    local: false
    keepMetricsWhenQueueManagerIsDown: false
    clearMetrics: 5
    ccdtFile1: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\@ipcc\AMQCLCHL.TAB
    alerts:
      highqueuedepth:
         action: MQIA_INHIBIT_PUT
         queues:
            queue:
              queueName: FRED
# percentage and value are mutually exclusive
              percentage: 60
            queue:
              queueName: "*"
              percentage: 80              
    json:
      sort: true
      order: ascending
    objects:
      queues:
        include: DEAD.LETTER.QUEUE, SYSTEM.ADMIN.COMMAND.QUEUE, SYSTEM.ADMIN.STATISTICS.QUEUE, SYSTEM.ADMIN.ACCOUNTING.QUEUE, "*"
        exclude: SYSTEM.,AMQ.,DUMMY,ERROR.HANDLER
      channels:
        include: "*"
        exclude: SYSTEM.
      listeners:
        include: "*"
        exclude: SYSTEM.
        types:
          include: TCP
          exclude: "*"         
    event:
      delayInMilliSeconds: 10000      
    security:
      truststore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01jks.jks
      truststore-password: Passw0rd
      keystore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01jks.jks
      keystore-password: Passw0rd
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus      
  endpoint:
    health:
      show-details: always
info:
  app:
    name: mq-metrics-1.0.0.16
    description: IBM MQ Metrics
    version: 1.0.0.16
    java:
      version: 1.8.0.0
server:
  port:
    8081