ibm:
  mq:
    queueManager: QMAP01
    channel: ADMIN.TLS.SVRCONN
    connName: localhost(1442)
    sslCipherSpec: TLS_RSA_WITH_AES_256_CBC_SHA256
    useSSL: false
    user: 
    password:
    objects:
      queues:
        include: "*"
        exclude: SYSTEM.,AMQ.,DUMMY,ERROR.HANDLER
      channels:
        include: "*"
        exclude: SYSTEM.
      listeners:
        include: "*"
        exclude: SYSTEM.
        types:
          include: TCP
          exclude: "*" 
    event:
      delayInMilliSeconds: 10000      
    security:
      truststore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01jks01.jks
      truststore-password: Passw0rd
      keystore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01jks01.jks
      keystore-password: Passw0rd
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
info:
  app:
    name: MQ-Metrics
    description: IBM MQ Metrics
    version: 1.0.0.0
    java:
      version: 1.8.0.0
server:
  port:
    8082