logging:
  level:
    org:
      springframework: OFF
    monitor:
      mq: INFO
application:
  save:
    metrics:
     required: false
     filename: c:\Users\mickm\eclipse-workspace\mq-metrics\mq-metrics\mySavedMetrics.json
spring:
  main:
    banner-mode: CONSOLE
  banner:
    location: banner.txt            
ibm:
  mq:
    multiInstance: false
    queueManager: QMAP03
    channel: MQ.NONTLS.MONITOR
    connName: localhost(1444)
    sslCipherSpec: TLS_RSA_WITH_AES_256_CBC_SHA256
    sslCipherSpec1: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    useSSL: false
    user: MQmon02
    password: Passw0rdPassw0rd1234
    authenticateUsingCSP: true
    local: false
    keepMetricsWhenQueueManagerIsDown: false
    clearMetrics: 5
    ccdtFile1: C:\ProgramData\IBM\MQ\qmgrs\QMAP03\@ipcc\AMQCLCHL.TAB    
    json:
      sort: true
      order: ascending
    objects:
      queues:
        include: "*"
        exclude: SYSTEM.,AMQ.,DUMMY,ERROR.HANDLER
      channels:
        include: "*"
        exclude: SYSTEM.,ADMIN.TLS.SVRCONN
      listeners:
        include: "*"
        exclude: SYSTEM.
        types:
          include: TCP
          exclude: "*"         
    event:
      delayInMilliSeconds: 10000      
    security:
      truststore: C:\ProgramData\IBM\MQ\qmgrs\QMAP03\ssl\qmap03jks.jks
      truststore-password: Passw0rd
      keystore: C:\ProgramData\IBM\MQ\qmgrs\QMAP03\ssl\qmap03jks.jks
      keystore-password: Passw0rd
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics      
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
info:
  app:
    name: MQ-Metrics
    description: IBM MQ Metrics
    version: 1.0.0.15
    java:
      version: 1.8.0.0
server:
  port:
    8093