logging:
  level:
    org:
      springframework: OFF
    monitor:
      mq: INFO
spring:
  main:
    banner-mode: CONSOLE
  banner:
    location: classpath:/banner.txt            
  security:
     user:
       name: monitor
       password: monitor123            
ibm:
  mq:
    multiInstance: true
    queueManager: QMAP01
    channel1: MQ.MONITOR.SVRCONN
    channel2: NOCRED_WITHCHLAUTH
    channel: MQ.JMS.SVRCONN
    connName: localhost(1501)
    sslCipherSpec2:
    sslCipherSpec1: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    sslCipherSpec3: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    sslCipherSpec: 
    ibmCipherMapping: false
    useSSL: false
    user: MQmon01
    password: Passw0rd
    authenticateUsingCSP: true
    local: false
    keepMetricsWhenQueueManagerIsDown: false
    resources:
      cpu: true
      system: true
    clearMetrics: 5
    ccdtFile1: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\@ipcc\AMQCLCHL.TAB
    alerts1:
      highqueuedepth:
         action: MQIA_INHIBIT_PUT
         value: percentage    
         queue: FRED:60, *:80
    json:
      sort: true
      order: ascending
    objects:
      epoch: 1
      queues:
        include: DEAD.LETTER.QUEUE, SYSTEM.ADMIN.COMMAND.QUEUE, SYSTEM.ADMIN.STATISTICS.QUEUE, SYSTEM.ADMIN.ACCOUNTING.QUEUE, "*"
        exclude: SYSTEM.,AMQ.,DUMMY,ERROR.HANDLER,KMQ.
      channels:
        include: "*"
        exclude: SYSTEM.
      listeners:
        include: "*"
        exclude: SYSTEM.
        types:
          include: TCP
          exclude: "*"         
    event:
      delayInMilliSeconds: 10000      
    security:
      truststore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01test.jks
      truststore-password: Passw0rd
      keystore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01test.jks
      keystore-password: Passw0rd
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus      
  endpoint:
    health:
      show-details: always
info:
  app:
    name: mq-metrics-1.0.0.18
    description: IBM MQ Metrics
    version: 1.0.0.18
    java:
      version: 1.8.0.0
server:
#  ssl:
#    key-store1: c:\Users\mickm\OneDrive\Documents\Development\tomcat\tomcat.p12
#    key-store-password1: Passw0rd
#    key-store-type1: pkcs12
#    key-alias1: mqevents
#    key-password1: Passw0rd  
  port: 8081